export CUDA_VISIBLE_DEVICES=0
cd ..
python -u run.py \
    --is_training 1 \
    --device cuda \
    --dataset_name human \
    --train_data_paths ./data/human/human \
    --valid_data_paths ./data/human/human \
    --save_dir checkpoints/human_MotionRNN_PredRNN_check \
    --gen_frm_dir results/human_MotionRNN_PredRNN_check \
    --model_name MotionRNN_PredRNN \
    --reverse_input 1 \
    --img_height 128 \
    --img_width 128 \
    --img_channel 3 \
    --input_length 4 \
    --total_length 8 \
    --num_hidden 64,64,64,64 \
    --filter_size 5 \
    --stride 1 \
    --patch_size 4 \
    --layer_norm 0 \
    --scheduled_sampling 1 \
    --sampling_stop_iter 50000 \
    --sampling_start_value 1.0 \
    --sampling_changing_rate 0.00002 \
    --lr 0.0003 \
    --batch_size 8 \
    --max_iterations 80000 \
    --display_interval 100 \
    --test_interval 5000 \
    --snapshot_interval 5000
